### PR TITLE
Added the ability to pass a callback to the minimizeCookieExposure configuration option.

### PR DESCRIPTION
**Pull request by joshrhykerd**

### CODE REVIEW

**Comment by tomcur** [comment]
I like it! Do you have a reason to pass an object with a named callable member `minimizeCookieExposure` instead of passing the callback directly? Passing callbacks directly might be a bit more flexible and eases implementation (e.g. allows for anonymous closures).

**Comment by joshrhykerd** [comment]
No I don't really have a reason other than I felt like it defined what it was used for, but I guess that can be left up to the user...

**Comment by joshrhykerd** [comment]
I guess kinda like if you saw it you knew what it was for instead of it getting lost. I dunno. We can def change it tho.

**Comment by tomcur** [comment]
Passing the callable directly might have a bit cleaner implementation. We can still have the example in the README be the way you have it now -- i.e. a `minimizeCookieExposure` member on the `AppController`, which is nice due to how explicit it is. Then we pass it as `$this->minimizeCookieExposure` to the configuration object.

**Comment by joshrhykerd** [comment]
Is this what you were looking for? I'm not sure if I did it the way you were asking or not...

**Comment by tomcur** [comment]
I slightly changed it so that a separate configuration entry is used. Otherwise if a user logs in and a token cookie is created, while for that request the callback indicates that no redirect should be performed, it then also accidentally indicates no minimization should be performed.

That would mean the cookie would be created insecurely. With two separate configuration entries we solve that problem.

**Comment by joshrhykerd** [comment]
Looks awesome! Thanks for letting me contribute and for writing the plugin to begin with!

**Comment by tomcur** [comment]
Thanks a lot for your contributions! They've made the plugin better. :)

I'll make a new release (2.1.0) soon with your changes.

**Pull request merged**
